import Link from "next/link";
import { ArrowRight, CheckCircle, CloudCheck, Fingerprint, FlowArrow, Gauge, LockKey, ShieldCheck } from "@phosphor-icons/react/dist/ssr";
import { AssuranceHero } from "@/components/assurance-hero";
import { MarketingFooter, MarketingHeader } from "@/components/marketing-shell";

const workflow = [
  ["01", "Interpret", "Gemini maps natural-language requirements to measurable controls."],
  ["02", "Inspect", "Dedicated identities collect current evidence from Google Cloud."],
  ["03", "Decide", "Deterministic policy separates safe automation from human approval."],
  ["04", "Fix", "The smallest drift-protected change executes asynchronously."],
  ["05", "Prove", "TrustFix independently tests the property and packages the evidence."],
];

export default function Landing() {
  return <main className="landing landing-v2"><MarketingHeader/><AssuranceHero/>
    <section className="trust-marquee"><div><span>BUILT ON GOOGLE CLOUD</span><strong>Gemini 3.5 Flash</strong><strong>Google ADK</strong><strong>Cloud Run</strong><strong>Firestore</strong><strong>Pub/Sub</strong><strong>Vertex AI</strong><strong>Google IAP</strong></div></section>
    <section className="experience-choice home-choice"><article><span className="status neutral">No login required</span><h3>Explore the complete story</h3><p>Walk through question → finding → approval → remediation → proof with clearly labeled illustrative data.</p><Link href="/demo">Launch interactive demo <ArrowRight/></Link></article><article><span className="status verified">Real Google Cloud</span><h3>Operate a protected workspace</h3><p>Inspect your disposable target, preserve evidence, approve governed changes, and export a Proof Pack.</p><a href="/app">Open real workspace <ArrowRight/></a></article></section>
    <section className="statement-section"><span className="section-index">THE PROBLEM</span><h2>AI can write a convincing security answer.<br/><em>That does not make it true.</em></h2><p>TrustFix closes the gap between what an organization claims and what its infrastructure actually proves. It does the operational work—not just the talking.</p></section>
    <section className="comparison-v2"><div className="old-way"><span>THE OLD WAY</span><h3>Generated claims</h3>{["Search stale documents", "Draft plausible language", "Assume the fix worked", "Rebuild evidence by hand"].map((item) => <p key={item}>{item}</p>)}</div><div className="versus">VS</div><div className="trustfix-way"><span>THE TRUSTFIX WAY</span><h3>Continuously proven</h3>{["Inspect live infrastructure", "Attach resource-specific proof", "Govern and execute the change", "Verify independently"].map((item) => <p key={item}><CheckCircle weight="fill"/>{item}</p>)}</div></section>
    <section className="workflow-v2" id="workflow"><header><span className="section-index">AUTONOMOUS OPERATING LOOP</span><h2>Observe. Decide. Fix. Prove.</h2><p>Reasoning where ambiguity exists. Deterministic controls where truth can be measured.</p></header><ol>{workflow.map(([index,title,copy]) => <li key={index}><span>{index}</span><div><strong>{title}</strong><p>{copy}</p></div></li>)}</ol></section>
    <section className="capability-stage" id="controls"><div className="capability-copy"><span className="section-index">DEEP, NOT DECORATIVE</span><h2>Autonomy with a safety case.</h2><p>TrustFix makes its authority visible. Every proposed mutation carries the exact delta, risk, dependencies, rollback, drift fingerprint, approval, and post-change verification.</p><Link href="/security">Explore the security architecture <ArrowRight/></Link></div><div className="capability-cards">{[[CloudCheck,"Live cloud inspection","Storage IAM, Cloud Run access, and firewall exposure."],[ShieldCheck,"Governed remediation","Role-aware approval and minimum-change execution."],[Fingerprint,"Evidence lineage","Timestamped proof connected to every final answer."],[Gauge,"Asynchronous operation","Pub/Sub workers handle long-running work safely."],[LockKey,"Separated authority","Scanner and remediator use dedicated identities."],[FlowArrow,"Portable Proof Packs","Export answers, evidence, approvals, and audit history."]].map(([Icon,title,copy]) => <article key={String(title)}><Icon/><h3>{String(title)}</h3><p>{String(copy)}</p></article>)}</div></section>
    <section className="architecture-v2"><header><span className="section-index">PRODUCTION-MINDED BY DESIGN</span><h2>One visible workflow.<br/>Six separated trust boundaries.</h2></header><div className="architecture-rail">{["Google IAP\nProtected identity","Next.js\nExperience layer","FastAPI\nControl plane","ADK + Gemini\nOrchestration","Pub/Sub workers\nSeparated authority","Disposable GCP\nTarget boundary"].map((item,index) => <div key={item}><span>{String(index + 1).padStart(2,"0")}</span><strong>{item.split("\n")[0]}</strong><small>{item.split("\n")[1]}</small></div>)}</div></section>
    <section className="final-cta final-cta-v2"><FlowArrow/><span className="section-index">FROM CLAIM TO PROOF</span><h2>See autonomous assurance<br/>finish the work.</h2><p>Explore publicly, then connect a disposable Google Cloud target when you are ready for live evidence.</p><div className="hero-actions"><Link className="button secondary" href="/demo">Explore without login</Link><a className="button primary" href="/app">Open protected workspace <ArrowRight/></a></div></section><MarketingFooter/>
  </main>;
}
