import { ArrowRight, CheckCircle, Cloud, Database, HardDrives, Info, LockKey, Warning } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";

type Kind = "evidence" | "activity" | "controls" | "findings" | "integrations" | "policies" | "team" | "system";
const copy: Record<Kind, [string,string]> = {
  evidence:["Evidence","Resource-specific proof collected during control checks and verification."], activity:["Activity","An append-oriented history of review and remediation decisions."], controls:["Control library","Deterministic checks currently supported for Google Cloud."], findings:["Findings","Security gaps that need remediation or manual review."], integrations:["Integrations","Connect the systems TrustFix can inspect and verify."], policies:["Remediation policies","Set deterministic approval boundaries for infrastructure changes."], team:["Team","Manage workspace access and security-review roles."], system:["System","Deployment state and production readiness signals."]
};
export function SectionPage({kind}:{kind:Kind}) { const [title,desc]=copy[kind]; return <main className="page section-page"><div className="page-heading"><div><span className="breadcrumb">ACME SECURITY / {title.toUpperCase()}</span><h1>{title}</h1><p>{desc}</p></div></div><Content kind={kind}/></main> }

function Content({kind}:{kind:Kind}) {
  if(kind==="controls") return <div className="cards-list">{[["Public cloud storage","GCP_STORAGE_PUBLIC_ACCESS","Bucket IAM · Public access prevention"],["Internal Cloud Run authentication","GCP_RUN_PUBLIC_INVOKER","Service IAM · Anonymous HTTP probe"],["Administrative port exposure","GCP_FIREWALL_ADMIN_EXPOSURE","Firewall rules · TCP 22 / 3389"]].map(([a,b,c])=><article key={b}><span className="control-icon"><LockKey/></span><div><h3>{a}</h3><code>{b}</code><p>{c}</p></div><span className="status verified">Supported</span></article>)}</div>;
  if(kind==="evidence") return <div className="data-panel"><div className="data-head"><strong>Collected evidence</strong><span className="preview-tag">PREVIEW DATA</span></div>{[["Public cloud storage","trustfix-public-storage-demo","allUsers has Storage Object Viewer","Just now"],["Cloud Run IAM","trustfix-public-run-demo","No public invoker binding","2 min ago"],["Compute Firewall API","trustfix-open-ssh-demo","No public administrative ports","3 min ago"]].map((r,i)=><div className="data-row" key={r[1]}><span className="evidence-source"><HardDrives/></span><div><strong>{r[0]}</strong><code>{r[1]}</code></div><p>{r[2]}</p><span>{r[3]}</span><span className={`status ${i?"verified":"failed"}`}>{i?"Verified":"Failed"}</span></div>)}</div>;
  if(kind==="activity") return <div className="data-panel activity-panel">{[["Control failed","Public storage access detected","Just now","fail"],["Bucket inspected","trustfix-public-storage-demo","1 min ago","normal"],["Environment scan started","Google Cloud target project","2 min ago","normal"],["Question mapped","GCP_STORAGE_PUBLIC_ACCESS","2 min ago","success"]].map(r=><div className="event" key={r[0]}><span className={`event-dot ${r[3]}`}/><div><strong>{r[0]}</strong><p>{r[1]}</p></div><time>{r[2]}</time></div>)}</div>;
  if(kind==="findings") return <div className="cards-list"><article><span className="finding-icon critical"><Warning/></span><div><h3>Public bucket detected</h3><code>trustfix-public-storage-demo</code><p>Anonymous principals can read objects.</p></div><Link className="button secondary" href="/app/reviews">Review <ArrowRight/></Link></article><article><span className="finding-icon high"><Cloud/></span><div><h3>Internal API publicly invokable</h3><code>trustfix-public-run-demo</code><p>Approval is required to remove the public invoker binding.</p></div><span className="status needs-review">Needs approval</span></article></div>;
  if(kind==="integrations") return <div className="integration-grid"><article className="featured"><Cloud size={28}/><div><h3>Google Cloud</h3><p>Live infrastructure inspection and governed remediation.</p></div><span className="status needs-review">Not connected</span><dl><div><dt>Project</dt><dd>—</dd></div><div><dt>Required boundary</dt><dd>Disposable target project</dd></div><div><dt>Authentication</dt><dd>Application Default Credentials</dd></div></dl><button className="button primary">Configure connection</button></article>{["Google Drive","Gmail","Slack"].map(x=><article key={x}><Database/><div><h3>{x}</h3><p>Optional questionnaire source.</p></div><span className="status neutral">Coming later</span></article>)}</div>;
  if(kind==="policies") return <div className="data-panel policy-list">{[["Public storage remediation","Require approval","Minimum IAM delta and public-access prevention"],["Cloud Run access remediation","Require approval","Remove only allUsers invoker"],["Firewall remediation","Always require approval","Disable labelled demo rule"]].map(r=><div className="data-row" key={r[0]}><span className="control-icon"><LockKey/></span><div><strong>{r[0]}</strong><p>{r[2]}</p></div><select defaultValue={r[1]} aria-label={`${r[0]} policy`}><option>Auto remediate low risk</option><option>Require approval</option><option>Always require approval</option><option>Manual only</option></select></div>)}</div>;
  if(kind==="system") return <div className="system-grid">{[["Environment","Development"],["Google Cloud project","Not configured"],["Cloud Run deployment","Not deployed"],["Active Gemini model","gemini-2.5-flash"],["Region","us-central1"],["Firestore status","Local adapter"],["Pub/Sub status","Local adapter"],["Last health check","Ready"]].map(([a,b])=><article key={a}><span>{a}</span><strong>{b}</strong>{b==="Ready"?<CheckCircle weight="fill"/>:<Info/>}</article>)}</div>;
  return <div className="empty-state"><Info size={28}/><h2>No additional workspace members yet</h2><p>Invite security reviewers after Google application authentication is configured.</p><button className="button primary">Invite team member</button></div>;
}

